version: '3'

services:
  landing:
    container_name: landing
    build:
      context: ./
      dockerfile: ./Dockerfile
    environment:
      - NODE_ENV
      - API_URL
    ports:
      - 3000:3000
    volumes:
      - ./src:/landing/src
      - ./public:/landing/public
      - ./.env:/landing/.env
      - ./package.json:/landing/package.json
    command: ["./node_modules/.bin/next", "start", "-p", "3000"]

  storybook:
    container_name: storybook
    build:
      context: ./
      dockerfile: ./.storybook/Dockerfile
    environment:
      - NODE_ENV
    ports:
      - 6006:6006
    volumes:
      - ./src:/storybook/src
      - ./public:/storybook/public
      - ./.env:/storybook/.env
      - ./package.json:/storybook/package.json
      - ./.storybook:/storybook/.storybook
    command: ["yarn", "storybook"]
