steps:
  - label: 'build landing'
    command:
      - "docker-compose build --build-arg API_URL=$API_URL --build-arg NODE_ENV=$NODE_ENV landing"

  - wait

  - label: 'start landing'
    command:
      - "API_URL=http://api:4000 NODE_ENV=production docker-compose up -d landing"
